; standard API, as defined in bootloader, starting from 0100H, every 3 bytes, in this order

SYSCALL ISDIGIT
SYSCALL ISLETTER
SYSCALL TOUPPER

SYSCALL PRINT
SYSCALL PRINT_CRLF
SYSCALL PRINTLN
SYSCALL PRINT_DEC
SYSCALL PRINT_NIBBLE
SYSCALL PRINT_HEX8
SYSCALL PRINT_HEX16
SYSCALL PRINTF
SYSCALL READLINE

SYSCALL MEMCMP
SYSCALL STRLEN
SYSCALL STRCMP
SYSCALL MEMCPY
SYSCALL ATOI
SYSCALL STRTOK
